language: java
jdk:
 - oraclejdk8 
sudo: false 
cache:
  directories:
   - $HOME/.m2
   - $HOME/.cache
   - $HOME/.gradle   
jobs:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers -DworkerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion -DappName=$appName