language: java
jdk:
    - openjdk8
  
env:
    - NODE_VERSION=12

cache:
    directories:
        - "$HOME/.cache"

jobs:
    include:
        - stage: deploy
        name: 'Deploy To CloudHub Development Environment'
        script:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn clean install deploy -DmuleDeploy -Dserver=$server -Denvironment=$environment -Dworkers=$workers -DworkerType=$workerType -DmuleVersion=$muleVersion -DappName=$appName
        
        